/* eslint-disable camelcase */
export const LANGUAGES: Record<string, string> = {
    ab: 'Abkhaze',
    ace: 'Aceh',
    ach: 'Acoli',
    ada: 'Adangme',
    ady: 'Adygh\u00e9en',
    aa: 'Afar',
    afh: 'Afrihili',
    af: 'Afrikaans',
    agq: 'Aghem',
    ain: 'A\u00efnou',
    ak: 'Akan',
    akk: 'Akkadien',
    bss: 'Akoose',
    akz: 'Alabama',
    sq: 'Albanais',
    ale: 'Al\u00e9oute',
    arq: 'Algerian Arabic',
    de: 'Allemand',
    de_AT: 'Allemand autrichien',
    de_CH: 'Allemand suisse',
    alt: 'Alta\u00ef du Sud',
    zgh: 'Amazighe standard marocain',
    ase: 'American Sign Language',
    am: 'Amharique',
    ang: 'Ancien anglais',
    fro: 'Ancien fran\u00e7ais',
    goh: 'Ancien haut allemand',
    sga: 'Ancien irlandais',
    anp: 'Angika',
    en: 'Anglais',
    en_US: 'Anglais am\u00e9ricain',
    en_AU: 'Anglais australien',
    en_GB: 'Anglais britannique',
    en_CA: 'Anglais canadien',
    njo: 'Ao Naga',
    ar: 'Arabe',
    ar_001: 'Arabe standard moderne',
    shu: 'Arabe tchadien',
    an: 'Aragonais',
    arc: 'Aram\u00e9en',
    sam: 'Aram\u00e9en samaritain',
    aro: 'Araona',
    arp: 'Arapaho',
    arn: 'Araukan',
    arw: 'Arawak',
    hy: 'Arm\u00e9nien',
    as: 'Assamais',
    asa: 'Assou',
    ast: 'Asturien',
    cch: 'Atsam',
    av: 'Avar',
    ae: 'Avestique',
    awa: 'Awadhi',
    ay: 'Aymara',
    az: 'Az\u00e9ri',
    ba: 'Bachkir',
    bfq: 'Badaga',
    ksf: 'Bafia',
    bfd: 'Bafut',
    bqi: 'Bakhtiari',
    ban: 'Balinais',
    bal: 'Baloutchi',
    bm: 'Bambara',
    bax: 'Bamoun',
    bjn: 'Banjar',
    nds: 'Bas-allemand',
    dsb: 'Bas-sorabe',
    eu: 'Basque',
    bas: 'Bassa',
    bbc: 'Batak Toba',
    bar: 'Bavarian',
    bej: 'Bedja',
    bem: 'Bemba',
    bez: 'B\u00e9na',
    bn: 'Bengali',
    bew: 'Betawi',
    bho: 'Bhojpuri',
    bi: 'Bichelamar',
    be: 'Bi\u00e9lorusse',
    bik: 'Bikol',
    bin: 'Bini',
    my: 'Birman',
    bpy: 'Bishnupriya',
    byn: 'Blin',
    brx: 'Bodo',
    bs: 'Bosniaque',
    bum: 'Boulou',
    bua: 'Bouriate',
    brh: 'Brahui',
    bra: 'Braj',
    br: 'Breton',
    bug: 'Bugi',
    bg: 'Bulgare',
    cad: 'Caddo',
    frc: 'Cajun French',
    yue: 'Cantonais',
    cps: 'Capiznon',
    kea: 'Capverdien',
    krl: 'Car\u00e9lien',
    car: 'Caribe',
    ca: 'Catalan',
    cay: 'Cayuga',
    ceb: 'Cebuano',
    dtp: 'Central Dusun',
    esu: 'Central Yupik',
    ksb: 'Chambala',
    ch: 'Chamorro',
    chr: 'Cherokee',
    chy: 'Cheyenne',
    chb: 'Chibcha',
    qug: 'Chimborazo Highland Quichua',
    zh: 'Chinois',
    zh_Hans: 'Chinois simplifi\u00e9',
    zh_Hant: 'Chinois traditionnel',
    chp: 'Chipewyan',
    shi: 'Chleuh',
    cho: 'Choctaw',
    chk: 'Chuuk',
    si: 'Cinghalais',
    swb: 'Comorien',
    cop: 'Copte',
    ko: 'Cor\u00e9en',
    kw: 'Cornique',
    co: 'Corse',
    cr: 'Cree',
    mus: 'Creek',
    mfe: 'Cr\u00e9ole mauricien',
    hr: 'Croate',
    dak: 'Dakota',
    da: 'Danois',
    dar: 'Dargwa',
    dzg: 'Dazaga',
    del: 'Delaware',
    din: 'Dinka',
    dyo: 'Diola-fogny',
    dyu: 'Dioula',
    doi: 'Dogri',
    dgr: 'Dogrib',
    dua: 'Douala',
    dz: 'Dzongkha',
    sco: '\u00e9cossais',
    efi: 'Efik',
    arz: 'Egyptian Arabic',
    egy: '\u00e9gyptien ancien',
    eka: 'Ekajuk',
    elx: '\u00e9lamite',
    ebu: 'Embou',
    egl: 'Emilian',
    myv: 'Erzya',
    es: 'Espagnol',
    es_ES: 'Espagnol europ\u00e9en',
    es_419: 'Espagnol latino-am\u00e9ricain',
    es_MX: 'Espagnol mexicain',
    eo: 'Esp\u00e9ranto',
    et: 'Estonien',
    ee: '\u00e9w\u00e9',
    ewo: '\u00e9wondo',
    ext: 'Extremaduran',
    fan: 'Fang',
    fat: 'Fanti',
    fo: 'F\u00e9ro\u00efen',
    fj: 'Fidjien',
    hif: 'Fiji Hindi',
    fil: 'Filipino',
    fi: 'Finnois',
    nl_BE: 'Flamand',
    fon: 'Fon',
    gur: 'Frafra',
    fr: 'Fran\u00e7ais',
    fr_CA: 'Fran\u00e7ais canadien',
    fr_CH: 'Fran\u00e7ais suisse',
    ksh: 'Francique ripuaire',
    frp: 'Franco-proven\u00e7al',
    fur: 'Frioulan',
    frr: 'Frison du Nord',
    fy: 'Frison occidental',
    frs: 'Frison oriental',
    gaa: 'Ga',
    gd: 'Ga\u00e9lique \u00e9cossais',
    gag: 'Gagaouze',
    gl: 'Galicien',
    cy: 'Gallois',
    gan: 'Gan Chinese',
    lg: 'Ganda',
    gay: 'Gayo',
    gba: 'Gbaya',
    ka: 'G\u00e9orgien',
    aln: 'Gheg Albanian',
    bbj: 'Ghomala',
    glk: 'Gilaki',
    gil: 'Gilbertais',
    gom: 'Goan Konkani',
    gon: 'Gondi',
    gor: 'Gorontalo',
    got: 'Gotique',
    grb: 'Grebo',
    el: 'Grec',
    grc: 'Grec ancien',
    kl: 'Groenlandais',
    gn: 'Guarani',
    gez: 'Gu\u00e8ze',
    gu: 'Gujarati',
    guz: 'Gusii',
    gwi: 'Gwich\u02bcin',
    hai: 'Haida',
    ht: 'Ha\u00eftien',
    hak: 'Hakka Chinese',
    ha: 'Haoussa',
    hsb: 'Haut-sorabe',
    haw: 'Hawa\u00efen',
    he: 'H\u00e9breu',
    hz: 'H\u00e9r\u00e9ro',
    hil: 'Hiligaynon',
    hi: 'Hindi',
    ho: 'Hiri motu',
    hit: 'Hittite',
    hmn: 'Hmong',
    hu: 'Hongrois',
    hup: 'Hupa',
    sah: 'Iakoute',
    iba: 'Iban',
    ibb: 'Ibibio',
    io: 'Ido',
    ig: 'Igbo',
    ilo: 'Ilokano',
    id: 'Indon\u00e9sien',
    inh: 'Ingouche',
    izh: 'Ingrian',
    ia: 'Interlingua',
    ie: 'Interlingue',
    iu: 'Inuktitut',
    ik: 'Inupiaq',
    ga: 'Irlandais',
    is: 'Islandais',
    it: 'Italien',
    jam: 'Jamaican Creole English',
    ja: 'Japonais',
    chn: 'Jargon chinook',
    jv: 'Javanais',
    kaj: 'Jju',
    jrb: 'Jud\u00e9o-arabe',
    jpr: 'Jud\u00e9o-persan',
    jut: 'Jutish',
    quc: 'K\u2019iche\u2019',
    kbd: 'Kabardin',
    kab: 'Kabyle',
    kac: 'Kachin',
    csb: 'Kachoube',
    kgp: 'Kaingang',
    kkj: 'Kako',
    kln: 'Kalenjin',
    xal: 'Kalmouk',
    kam: 'Kamba',
    kbl: 'Kanembou',
    kn: 'Kannada',
    kr: 'Kanouri',
    kaa: 'Karakalpak',
    krc: 'Karatcha\u00ef balkar',
    ks: 'Kashmiri',
    kaw: 'Kawi',
    kk: 'Kazakh',
    ken: 'Kenyang',
    kha: 'Khasi',
    km: 'Khmer',
    kho: 'Khotanais',
    khw: 'Khowar',
    cgg: 'Kiga',
    ki: 'Kikuyu',
    kmb: 'KiMboundou',
    krj: 'Kinaray-a',
    ky: 'Kirghize',
    kiu: 'Kirmanjki',
    tlh: 'Klingon',
    bkm: 'Kom',
    kv: 'Komi',
    koi: 'Komi-permiak',
    kg: 'Kongo',
    kok: 'Konkani',
    kfo: 'Koro',
    avk: 'Kotava',
    kum: 'Koumyk',
    khq: 'Koyra chiini',
    ses: 'Koyraboro senni',
    kpe: 'Kpell\u00e9',
    kri: 'Krio',
    kj: 'Kuanyama',
    ku: 'Kurde',
    kru: 'Kurukh',
    kos: 'Kusaien',
    kut: 'Kutenai',
    nmg: 'Kwasio',
    lad: 'Ladino',
    lah: 'Lahnda',
    lkt: 'Lakota',
    lam: 'Lamba',
    lag: 'Langi',
    und: 'Langue ind\u00e9termin\u00e9e',
    lo: 'Lao',
    ltg: 'Latgalian',
    la: 'Latin',
    lzz: 'Laz',
    lv: 'Letton',
    lez: 'Lezghien',
    lij: 'Ligurian',
    li: 'Limbourgeois',
    ln: 'Lingala',
    lfn: 'Lingua Franca Nova',
    lzh: 'Literary Chinese',
    lt: 'Lituanien',
    liv: 'Livonian',
    jbo: 'Lojban',
    lmo: 'Lombard',
    sli: 'Lower Silesian',
    loz: 'Lozi',
    lu: 'Luba-katanga',
    lua: 'Luba-lulua',
    lui: 'Luiseno',
    lun: 'Lunda',
    luo: 'Luo',
    lus: 'Lushai',
    lb: 'Luxembourgeois',
    mde: 'Maba',
    mk: 'Mac\u00e9donien',
    jmc: 'Machame',
    mad: 'Madurais',
    maf: 'Mafa',
    mag: 'Magahi',
    vmf: 'Main-Franconian',
    mai: 'Maithili',
    mak: 'Makassar',
    mgh: 'Makhuwa-meetto',
    kde: 'Makonde',
    ms: 'Malais',
    ml: 'Malayalam',
    dv: 'Maldivien',
    mg: 'Malgache',
    mt: 'Maltais',
    mdr: 'Mandar',
    mnc: 'Mandchou',
    man: 'Mandingue',
    mni: 'Manipuri',
    gv: 'Manx',
    mi: 'Maori',
    mr: 'Marathe',
    chm: 'Mari',
    mh: 'Marshall',
    mwr: 'Marwar\u00ee',
    mas: 'Masai',
    mzn: 'Mazanderani',
    byv: 'Medumba',
    men: 'Mend\u00e9',
    mwv: 'Mentawai',
    mer: 'Merou',
    mgo: 'M\u00e9ta\u2019',
    mic: 'Micmac',
    nan: 'Min Nan Chinese',
    min: 'Minangkabau',
    xmf: 'Mingrelian',
    mwl: 'Mirandais',
    moh: 'Mohawk',
    mdf: 'Moksa',
    ro_MD: 'Moldave',
    lol: 'Mongo',
    mn: 'Mongol',
    mos: 'Mor\u00e9',
    ary: 'Moroccan Arabic',
    enm: 'Moyen anglais',
    frm: 'Moyen fran\u00e7ais',
    gmh: 'Moyen haut-allemand',
    mga: 'Moyen irlandais',
    dum: 'Moyen n\u00e9erlandais',
    mul: 'Multilingue',
    mua: 'Mundang',
    ttt: 'Muslim Tat',
    mye: 'My\u00e8n\u00e8',
    nqo: 'N\u2019ko',
    naq: 'Nama',
    nap: 'Napolitain',
    na: 'Nauruan',
    nv: 'Navaho',
    nd: 'Nd\u00e9b\u00e9l\u00e9 du Nord',
    nr: 'Nd\u00e9b\u00e9l\u00e9 du Sud',
    ng: 'Ndonga',
    nl: 'N\u00e9erlandais',
    ne: 'N\u00e9palais',
    new: 'Newari',
    nwc: 'Newar\u00ee classique',
    sba: 'Ngambay',
    nnh: 'Ngiemboon',
    jgo: 'Ngomba',
    yrl: 'Nheengatu',
    nia: 'Nias',
    niu: 'Niu\u00e9',
    nog: 'Noga\u00ef',
    no: 'Norv\u00e9gien',
    nb: 'Norv\u00e9gien bokm\u00e5l',
    nn: 'Norv\u00e9gien nynorsk',
    nov: 'Novial',
    nus: 'Nuer',
    nym: 'Nyamwezi',
    ny: 'Nyanja',
    nyn: 'Nyankol\u00e9',
    nyo: 'Nyoro',
    nzi: 'Nzema',
    oc: 'Occitan',
    oj: 'Ojibwa',
    luy: 'Oluluyia',
    or: 'Oriya',
    om: 'Oromo',
    osa: 'Osage',
    os: 'Oss\u00e8te',
    udm: 'Oudmourte',
    uga: 'Ougaritique',
    ug: 'Ou\u00efghour',
    ur: 'Ourdou',
    uz: 'Ouzbek',
    ps: 'Pachto',
    pal: 'Pahlavi',
    pfl: 'Palatine German',
    pau: 'Palau',
    pi: 'Pali',
    pam: 'Pampangan',
    pag: 'Pangasinan',
    pap: 'Papiamento',
    pa: 'Pendjabi',
    pdc: 'Pennsylvania German',
    fa: 'Persan',
    peo: 'Persan ancien',
    ff: 'Peul',
    phn: 'Ph\u00e9nicien',
    pcd: 'Picard',
    pms: 'Piedmontese',
    pdt: 'Plautdietsch',
    pon: 'Pohnpei',
    pl: 'Polonais',
    pnt: 'Pontic',
    pt: 'Portugais',
    pt_BR: 'Portugais br\u00e9silien',
    pt_PT: 'Portugais europ\u00e9en',
    pro: 'Proven\u00e7al ancien',
    prg: 'Prussian',
    qu: 'Quechua',
    root: 'Racine',
    raj: 'Rajasthani',
    rap: 'Rapanui',
    rar: 'Rarotongien',
    rif: 'Riffian',
    rgn: 'Romagnol',
    rm: 'Romanche',
    rof: 'Rombo',
    rtm: 'Rotuman',
    ro: 'Roumain',
    rn: 'Roundi',
    rug: 'Roviana',
    ru: 'Russe',
    rue: 'Rusyn',
    rwk: 'Rwa',
    rw: 'Rwanda',
    ssy: 'Saho',
    saq: 'Samburu',
    smn: 'Sami d\u2019Inari',
    smj: 'Sami de Lule',
    se: 'Sami du Nord',
    sma: 'Sami du Sud',
    sms: 'Sami skolt',
    sm: 'Samoan',
    sgs: 'Samogitian',
    sad: 'Sandawe',
    sg: 'Sangho',
    sbp: 'Sangu',
    zxx: 'Sans contenu linguistique',
    sa: 'Sanskrit',
    sat: 'Santal',
    sc: 'Sarde',
    sas: 'Sasak',
    sdc: 'Sassarese Sardinian',
    stq: 'Saterland Frisian',
    saz: 'Saurashtra',
    sly: 'Selayar',
    sel: 'Selkoupe',
    seh: 'Sena',
    see: 'Seneca',
    sr: 'Serbe',
    sh: 'Serbo-croate',
    srr: 'S\u00e9r\u00e8re',
    sei: 'Seri',
    st: 'Sesotho',
    shn: 'Shan',
    sn: 'Shona',
    scn: 'Sicilien',
    sid: 'Sidamo',
    bla: 'Siksika',
    szl: 'Silesian',
    sd: 'Sindhi',
    den: 'Slavey',
    cu: 'Slavon d\u2019\u00e9glise',
    sk: 'Slovaque',
    sl: 'Slov\u00e8ne',
    xog: 'Soga',
    sog: 'Sogdien',
    so: 'Somali',
    snk: 'Sonink\u00e9',
    ckb: 'Sorani',
    nso: 'Sotho du Nord',
    su: 'Soundanais',
    sus: 'Soussou',
    azb: 'South Azerbaijani',
    srn: 'Sranan tongo',
    sv: 'Su\u00e9dois',
    gsw: 'Suisse allemand',
    suk: 'Sukuma',
    sux: 'Sum\u00e9rien',
    sw: 'Swahili',
    swc: 'Swahili du Congo',
    ss: 'Swati',
    zbl: 'Symboles Bliss',
    syr: 'Syriaque',
    syc: 'Syriaque classique',
    tg: 'Tadjik',
    tl: 'Tagalog',
    ty: 'Tahitien',
    dav: 'Taita',
    tly: 'Talysh',
    tmh: 'Tamacheq',
    tzm: 'Tamazight',
    ta: 'Tamoul',
    trv: 'Taroko',
    twq: 'Tasawaq',
    tt: 'Tatar',
    chg: 'Tchaghata\u00ef',
    cs: 'Tch\u00e8que',
    ce: 'Tch\u00e9tch\u00e8ne',
    cv: 'Tchouvache',
    te: 'T\u00e9lougou',
    tem: 'Temne',
    ter: 'Tereno',
    teo: 'Teso',
    tet: 'Tetum',
    th: 'Tha\u00ef',
    bo: 'Tib\u00e9tain',
    tig: 'Tigr\u00e9',
    ti: 'Tigrigna',
    tiv: 'Tiv',
    tli: 'Tlingit',
    tpi: 'Tok pisin',
    tkl: 'Tokelau',
    tog: 'Tonga nyasa',
    to: 'Tonguien',
    fit: 'Tornedalen Finnish',
    tyv: 'Touva',
    tkr: 'Tsakhur',
    tsd: 'Tsakonian',
    tsi: 'Tsimshian',
    ts: 'Tsonga',
    tn: 'Tswana',
    tcy: 'Tulu',
    tum: 'Tumbuka',
    aeb: 'Tunisian Arabic',
    tr: 'Turc',
    crh: 'Turc de Crim\u00e9e',
    ota: 'Turc ottoman',
    tk: 'Turkm\u00e8ne',
    tru: 'Turoyo',
    tvl: 'Tuvalu',
    tw: 'Twi',
    kcg: 'Tyap',
    rom: 'Tzigane',
    uk: 'Ukrainien',
    umb: 'Umbundu',
    vai: 'Va\u00ef',
    rup: 'Valaque',
    ve: 'Venda',
    vec: 'Venetian',
    vep: 'Veps',
    vi: 'Vietnamien',
    non: 'Vieux norrois',
    vo: 'Volapuk',
    vro: 'V\u00f5ro',
    vot: 'Vote',
    vun: 'Vunjo',
    wal: 'Walamo',
    wa: 'Wallon',
    wae: 'Walser',
    war: 'Waray',
    wbp: 'Warlpiri',
    was: 'Washo',
    guc: 'Wayuu',
    vls: 'West Flemish',
    mrj: 'Western Mari',
    wo: 'Wolof',
    wuu: 'Wu Chinese',
    xh: 'Xhosa',
    hsn: 'Xiang Chinese',
    yav: 'Yangben',
    yao: 'Yao',
    yap: 'Yapois',
    ybb: 'Yemba',
    ii: 'Yi du Sichuan',
    yi: 'Yiddish',
    yo: 'Yoruba',
    zap: 'Zapot\u00e8que',
    dje: 'Zarma',
    zza: 'Zazaki',
    zea: 'Zeelandic',
    zen: 'Zenaga',
    za: 'Zhuang',
    gbz: 'Zoroastrian Dari',
    zu: 'Zoulou',
    zun: 'Zuni',
};
