export const COUNTRIES: Partial<Record<string, string>> = {
    AF: 'Afghanistan',
    ZA: 'Afrique du Sud',
    AL: 'Albanie',
    DZ: 'Algérie',
    DE: 'Allemagne',
    AO: 'Angola',
    AD: 'Andorre',
    AG: 'Antigua-Et-Barbuda',
    SA: 'Arabie Saoudite',
    AR: 'Argentine',
    AM: 'Arménie',
    AU: 'Australie',
    AT: 'Autriche',
    AZ: 'Azerbaïdjan',
    BS: 'Bahamas',
    BH: 'Bahreïn',
    BD: 'Bangladesh',
    BB: 'Barbade',
    BE: 'Belgique',
    BZ: 'Belize',
    BJ: 'Bénin',
    BT: 'Bhoutan',
    BY: 'Biélorussie',
    MM: 'Birmanie',
    BO: 'État Plurinational De Bolivie',
    BA: 'Bosnie-Herzégovine',
    BW: 'Botswana',
    BR: 'Brésil',
    BN: 'Brunei Darussalam',
    BG: 'Bulgarie',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    KH: 'Cambodge',
    CM: 'Cameroun',
    CA: 'Canada',
    CV: 'Cap-Vert',
    CF: 'République Centrafricaine',
    CL: 'Chili',
    CN: 'Chine',
    CY: 'Chypre',
    CO: 'Colombie',
    KM: 'Comores',
    CG: 'Congo',
    CD: 'République Démocratique Du Congo',
    CK: 'Îles Cook',
    KP: 'République Populaire Démocratique De Corée',
    KR: 'République De Corée',
    CR: 'Costa Rica',
    CI: "Côte D'Ivoire",
    HR: 'Croatie',
    CU: 'Cuba',
    DK: 'Danemark',
    DJ: 'Djibouti',
    DO: 'République Dominicaine',
    DM: 'Dominique',
    EG: 'Égypte',
    AE: 'Émirats Arabes Unis',
    EC: 'Équateur',
    ER: 'Érythrée',
    ES: 'Espagne',
    EE: 'Estonie',
    SZ: 'Swaziland',
    US: 'États-Unis',
    ET: 'Éthiopie',
    FJ: 'Fidji',
    FI: 'Finlande',
    FR: 'France',
    GA: 'Gabon',
    GM: 'Gambie',
    GE: 'Géorgie',
    GH: 'Ghana',
    GR: 'Grèce',
    GD: 'Grenade',
    GT: 'Guatemala',
    GN: 'Guinée',
    GQ: 'Guinée Équatoriale',
    GW: 'Guinée-Bissau',
    GY: 'Guyana',
    HT: 'Haïti',
    HN: 'Honduras',
    HU: 'Hongrie',
    IN: 'Inde',
    ID: 'Indonésie',
    IQ: 'Irak',
    IR: "République Islamique D'Iran",
    IE: 'Irlande',
    IS: 'Islande',
    IL: 'Israël',
    IT: 'Italie',
    JM: 'Jamaïque',
    JP: 'Japon',
    JO: 'Jordanie',
    KG: 'Kirghizistan',
    KI: 'Kiribati',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KW: 'Koweït',
    LA: 'République Démocratique Populaire Lao',
    LS: 'Lesotho',
    LV: 'Lettonie',
    LB: 'Liban',
    LR: 'Liberia',
    LY: 'Libye',
    LI: 'Liechtenstein',
    LT: 'Lituanie',
    LU: 'Luxembourg',
    MG: 'Madagascar',
    MK: 'Macédoine Du Nord',
    MY: 'Malaisie',
    MW: 'Malawi',
    MV: 'Maldives',
    ML: 'Mali',
    MT: 'Malte',
    MA: 'Maroc',
    MH: 'Marshall',
    MU: 'Maurice',
    MR: 'Mauritanie',
    MX: 'Mexique',
    FM: 'États Fédérés De Micronésie',
    MC: 'Monaco',
    MD: 'République De Moldavie',
    ME: 'Monténégro',
    MN: 'Mongolie',
    MZ: 'Mozambique',
    NA: 'Namibie',
    NR: 'Nauru',
    NP: 'Népal',
    NE: 'Niger',
    NG: 'Nigéria',
    NI: 'Nicaragua',
    NU: 'Niue',
    NO: 'Norvège',
    NZ: 'Nouvelle-Zélande',
    OM: 'Oman',
    UG: 'Ouganda',
    UZ: 'Ouzbékistan',
    PK: 'Pakistan',
    PW: 'Palaos',
    PS: 'Palestine',
    PA: 'Panama',
    PG: 'Papouasie-Nouvelle-Guinée',
    PY: 'Paraguay',
    PE: 'Pérou',
    NL: 'Pays-Bas',
    PH: 'Philippines',
    PL: 'Pologne',
    PT: 'Portugal',
    QA: 'Qatar',
    RO: 'Roumanie',
    GB: 'Royaume-Uni',
    RU: 'Russie',
    RW: 'Rwanda',
    KN: 'Saint-Christophe-et-Niévès',
    LC: 'Sainte-Lucie',
    SM: 'Saint-Marin',
    VC: 'Saint-Vincent-Et-Les Grenadines',
    SB: 'Îles Salomon',
    SV: 'République Du Salvador',
    WS: 'Samoa',
    ST: 'Sao Tomé-Et-Principe',
    SN: 'Sénégal',
    RS: 'Serbie',
    SC: 'Seychelles',
    SL: 'Sierra Leone',
    SG: 'Singapour',
    SK: 'Slovaquie',
    SI: 'Slovénie',
    SO: 'Somalie',
    SD: 'Soudan',
    SS: 'Soudan Du Sud',
    LK: 'Sri Lanka',
    SE: 'Suède',
    CH: 'Suisse',
    SR: 'Suriname',
    SY: 'République Arabe Syrienne',
    TJ: 'Tadjikistan',
    TZ: 'République-Unie De Tanzanie',
    TD: 'Tchad',
    CZ: 'République Tchèque',
    TH: 'Thaïlande',
    TL: 'Timor-Leste',
    TG: 'Togo',
    TO: 'Tonga',
    TT: 'Trinité-Et-Tobago',
    TN: 'Tunisie',
    TM: 'Turkménistan',
    TR: 'Turquie',
    TV: 'Tuvalu',
    UA: 'Ukraine',
    UY: 'Uruguay',
    VU: 'Vanuatu',
    VA: 'Saint-Siège (État De La Cité Du Vatican)',
    VE: 'Venezuela',
    VN: 'Viet Nam',
    YE: 'Yémen',
    ZM: 'Zambie',
    ZW: 'Zimbabwe',
};
