export const CURRENCIES: Record<string, string> = {
    AFN: 'Afghani',
    MGA: 'Ariary Malgache',
    AWG: 'Aruban Florin',
    AZN: 'Azerbaijanian Manat',
    THB: 'Baht',
    PAB: 'Balboa',
    ETB: 'Birr Éthiopienne',
    VEF: 'Bolivar',
    BOB: 'Boliviano',
    BND: 'Brunei Dollar',
    CVE: 'Cabo Verde Escudo',
    KYD: 'Cayman Islands Dollar',
    GHS: 'Cedi du Ghana',
    NIO: 'Cordoba',
    CRC: 'Costa Rican Colon',
    DKK: 'Couronne Danoise',
    ISK: 'Couronne Islandaise',
    NOK: 'Couronne Norvégienne',
    SEK: 'Couronne Suédoise',
    CZK: 'Couronne Tchèque',
    GMD: 'Dalasi',
    MKD: 'Denar',
    BHD: 'Dinar Bahraini',
    IQD: 'Dinar Iraquien',
    JOD: 'Dinar Jordanien',
    KWD: 'Dinar Koweïtien',
    LYD: 'Dinar Libien',
    RSD: 'Dinar Serbe',
    TND: 'Dinar Tunisiens',
    DZD: 'Dinar algériens',
    MAD: 'Dirham Marocain',
    AED: 'Dirham UAE',
    STD: 'Dobra',
    AUD: 'Dollar Australien',
    BSD: 'Dollar Bahaméen',
    BMD: 'Dollar Bermudien',
    CAD: 'Dollar Canadien',
    NAD: 'Dollar Namibien',
    SGD: 'Dollar Singaporien',
    USD: 'Dollar US',
    BZD: 'Dollar de Bélize',
    HKD: 'Dollar de Hong Kong',
    XCD: 'Dollar des Caraïbes orienta',
    FJD: 'Dollar des Fiji',
    SBD: 'Dollar des îles Solomon',
    LRD: 'Dollar du Liberia',
    GYD: 'Dollar guyanien',
    NZD: 'Dollar néo-zélandais',
    BBD: 'Dollars Barbados',
    JMD: 'Dollars Jamaïcain',
    TTD: 'Dollars de Trinidad et Tobago',
    SRD: 'Dollars du Surinam',
    ZWL: 'Dollars du Zimbabwe',
    VND: 'Dong',
    AMD: 'Dram Armenien',
    EUR: 'Euros',
    ANG: 'Florin des Antilles néerlandaises',
    HUF: 'Forint',
    BIF: 'Franc Burundi',
    XOF: 'Franc CFA (XOF)',
    XAF: 'Franc CFA (XAF)',
    XPF: 'Franc CFP',
    KMF: 'Franc Comorien',
    DJF: 'Franc Djiboutien',
    GNF: 'Franc Guinéen',
    RWF: 'Franc Rwandais',
    CHF: 'Franc Suisse',
    HTG: 'Gourde',
    PYG: 'Guarani',
    UAH: 'Hryvnia',
    PGK: 'Kina',
    LAK: 'Kip',
    HRK: 'Kuna',
    MWK: 'Kwacha',
    ZMW: 'Kwacha Zambien',
    AOA: 'Kwanza',
    MMK: 'Kyat',
    GEL: 'Lari',
    ALL: 'Lek',
    HNL: 'Lempira',
    SLL: 'Leone',
    MDL: 'Leu Moldavien',
    RON: 'Leu Roumain',
    BGN: 'Lev Bulgare',
    SZL: 'Lilangeni',
    SDG: 'Livre Soudanaise',
    GBP: 'Livre Sterling',
    TRY: 'Livre Turque',
    FKP: 'Livre des Îles Malouines',
    SSP: 'Livre sud-soudanaise',
    TMT: 'Manat turkmène',
    BAM: 'Mark Convertible',
    MUR: 'Mauritius Roupie',
    MZN: 'Metical',
    BOV: 'Mvdol',
    NGN: 'Naira',
    ERN: 'Nakfa',
    BTN: 'Ngultrum',
    ILS: 'Nouveau Sheqel Israélien',
    PEN: 'Nouveau Sol',
    TWD: 'Nouveau dollars Taiwanais',
    MRO: 'Ouguiya',
    MOP: 'Pataca',
    TOP: 'Pa’anga',
    ARS: 'Peso Argentin',
    CLP: 'Peso Chilien',
    COP: 'Peso Colombien',
    CUC: 'Peso Convertible',
    CUP: 'Peso Cubain',
    DOP: 'Peso Dominicain',
    MXN: 'Peso Mexicain',
    PHP: 'Peso Phillipins',
    UYU: 'Peso Uruguayen',
    LBP: 'Livre Libanaise',
    SYP: 'Livre Syrienne',
    GIP: 'Livre de Gibraltar',
    EGP: 'Livre Égyptienne',
    BWP: 'Pula',
    GTQ: 'Quetzal',
    ZAR: 'Rand',
    BRL: 'Real Brésilien',
    IRR: 'Rial Iranien',
    OMR: 'Rial Omani',
    QAR: 'Rial Qatari',
    YER: 'Rial du Yemenl',
    KHR: 'Riel',
    MYR: 'Ringgit Malaisien',
    SAR: 'Riyal Saoudiens',
    RUB: 'Rouble Russe',
    INR: 'Roupie Indienne',
    IDR: 'Roupie Indonésienne',
    NPR: 'Roupie Népalais',
    LKR: 'Roupie Sri Lankais',
    PKR: 'Roupie du Pakistan',
    SCR: 'Roupie seychelloise',
    BYR: 'Ruble Biélorusse',
    MVR: 'Rufiyaa',
    KES: 'Shilling Kenyan',
    UGX: 'Shilling Ougandaisg',
    SOS: 'Shilling Somalien',
    TZS: 'Shilling Tanzanien',
    KGS: 'Som',
    TJS: 'Somoni',
    UZS: 'Sum d’Oubekistan',
    BDT: 'Taka',
    WST: 'Tala',
    KZT: 'Tenge',
    MNT: 'Tugrik',
    VUV: 'Vatu',
    KRW: 'Won',
    KPW: 'Won Nord-coréen',
    JPY: 'Yen',
    CNY: 'Yuan Renminbi',
    PLN: 'Zloty',
};
